[tool.poetry]
name = "news-api-email"
version = "0.1.0"
description = ""
authors = ["≈Åukasz Kuk <lukasz010420@gmail.com>"]
readme = "README.md"
packages = [{include = "news_api_email"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
